-- ============================================================================
-- AQUALINK - ESTRUTURA DO BANCO DE DADOS SUPABASE
-- Sistema de Monitoramento de Água e Dessalinizador
-- 
-- INSTRUÇÕES DE EXECUÇÃO:
-- 1. Acesse o painel do Supabase: https://supabase.com/dashboard
-- 2. Selecione o seu projeto (oihzayyjpczdmocsxzgz)
-- 3. No menu lateral esquerdo, clique no ícone "SQL Editor" (ícone de terminal)
-- 4. Clique em "+ New query"
-- 5. Cole todo o conteúdo deste arquivo e clique no botão verde "Run" (ou Ctrl + Enter)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TABELA: device_state (Estado em tempo real da Caixa d'Água e Dessalinizador)
-- Guarda o snapshot mais recente enviado pelo ESP8266 Mestre
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.device_state (
    device_id TEXT PRIMARY KEY,
    nivel INTEGER NOT NULL DEFAULT 0,
    boia_mecanica BOOLEAN NOT NULL DEFAULT FALSE,
    deve_ligar BOOLEAN NOT NULL DEFAULT FALSE,
    rele1 BOOLEAN NOT NULL DEFAULT FALSE,
    rele2 BOOLEAN NOT NULL DEFAULT FALSE,
    led1 BOOLEAN NOT NULL DEFAULT FALSE,
    led2 BOOLEAN NOT NULL DEFAULT FALSE,
    fluxo_l_min NUMERIC(6,2) NOT NULL DEFAULT 0.00,
    fluxo_ok BOOLEAN NOT NULL DEFAULT FALSE,
    erro_fluxo BOOLEAN NOT NULL DEFAULT FALSE,
    modo INTEGER NOT NULL DEFAULT 0, -- 0: Auto, 1: Manual Ligado, 2: Manual Desligado
    estado_processo INTEGER NOT NULL DEFAULT 0,
    boia_online BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilita REPLICA IDENTITY FULL para que o Realtime envie todos os campos alterados
ALTER TABLE public.device_state REPLICA IDENTITY FULL;

-- ----------------------------------------------------------------------------
-- 2. TABELA: control_commands (Fila de comandos remotos enviados pelo Web App)
-- O Web App insere o comando e o ESP8266 Mestre lê, executa e marca como executado
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.control_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL DEFAULT 'dessalinizador_0001',
    command TEXT NOT NULL, -- 'manual_on', 'manual_off', 'auto'
    duration_seconds INTEGER DEFAULT 0,
    executed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    executed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_control_commands_pending 
ON public.control_commands (device_id, executed, id ASC);

-- ----------------------------------------------------------------------------
-- 3. TABELA: telemetry_history (Histórico cronológico de telemetria)
-- Permite gráficos históricos e relatórios de produção de água
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.telemetry_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL,
    nivel INTEGER NOT NULL,
    fluxo_l_min NUMERIC(6,2) NOT NULL DEFAULT 0.00,
    rele1 BOOLEAN NOT NULL,
    rele2 BOOLEAN NOT NULL,
    boia_mecanica BOOLEAN NOT NULL,
    modo INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_telemetry_history_time 
ON public.telemetry_history (device_id, created_at DESC);

-- ----------------------------------------------------------------------------
-- 4. SEGURANÇA: ROW LEVEL SECURITY (RLS)
-- Políticas para permitir leitura e escrita da chave anônima/publishable
-- ----------------------------------------------------------------------------
ALTER TABLE public.device_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.control_commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_history ENABLE ROW LEVEL SECURITY;

-- Remove políticas antigas se existirem para evitar duplicidade
DROP POLICY IF EXISTS "Permitir tudo em device_state" ON public.device_state;
DROP POLICY IF EXISTS "Permitir tudo em control_commands" ON public.control_commands;
DROP POLICY IF EXISTS "Permitir tudo em telemetry_history" ON public.telemetry_history;

-- Políticas de acesso livre para a chave publishable do sistema
CREATE POLICY "Permitir tudo em device_state"
ON public.device_state
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Permitir tudo em control_commands"
ON public.control_commands
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Permitir tudo em telemetry_history"
ON public.telemetry_history
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- ----------------------------------------------------------------------------
-- 5. ATIVAÇÃO DO SUPABASE REALTIME (WebSockets instantâneos)
-- Permite que o Web App receba alterações em tempo real sem fazer polling
-- ----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'device_state'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.device_state;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'control_commands'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.control_commands;
  END IF;
END $$;

-- ----------------------------------------------------------------------------
-- 6. REGISTRO INICIAL DO DISPOSITIVO
-- Garante que já exista uma linha inicial pronta para ser consumida pelo Web App
-- ----------------------------------------------------------------------------
INSERT INTO public.device_state (
    device_id,
    nivel,
    boia_mecanica,
    deve_ligar,
    rele1,
    rele2,
    led1,
    led2,
    fluxo_l_min,
    fluxo_ok,
    erro_fluxo,
    modo,
    estado_processo,
    boia_online,
    updated_at
) VALUES (
    'dessalinizador_0001',
    50,
    false,
    false,
    false,
    false,
    false,
    false,
    0.00,
    false,
    false,
    0,
    0,
    true,
    NOW()
)
ON CONFLICT (device_id) DO NOTHING;
